import { Neighborhood } from "../types/neighborhood";

export const neighborhoods: Neighborhood[] = [
  {
    id: 1,
    name: "Greenwood",
    city: "Springfield",
    averageRent: 1200,
    crimeIndex: 2.1,
    walkability: 4.5,
    greenSpaces: 4.8,
    distanceToBusinessHub: 3.2,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 2,
    name: "Downtown",
    city: "Springfield",
    averageRent: 1800,
    crimeIndex: 3.5,
    walkability: 4.9,
    greenSpaces: 2.2,
    distanceToBusinessHub: 1.0,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 3,
    name: "Lakeside",
    city: "Springfield",
    averageRent: 1400,
    crimeIndex: 1.8,
    walkability: 3.8,
    greenSpaces: 4.9,
    distanceToBusinessHub: 5.5,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 4,
    name: "Uptown",
    city: "Springfield",
    averageRent: 1600,
    crimeIndex: 2.9,
    walkability: 4.2,
    greenSpaces: 3.1,
    distanceToBusinessHub: 2.0,
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 5,
    name: "Suburbia",
    city: "Springfield",
    averageRent: 1000,
    crimeIndex: 1.2,
    walkability: 2.5,
    greenSpaces: 4.7,
    distanceToBusinessHub: 8.0,
    createdAt: "",
    updatedAt: "",
  },
];
